modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "bendylib"
version = "${version}"
displayName = "Bendy lib"
authors = "KosmX"
description = '''
Bendy API ported to Forge
But you should use Fabric or Quilt
'''
#logoFile = ""

[[dependencies.bendylib]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bendylib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "CLIENT"
