modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "CC-BY-4.0"

[[mods]]
modId = "bendylib"
version = "${version}"
displayURL = "https://github.com/KosmX/bendy-lib"
displayName = "Bendy lib"
authors = "KosmX"
description = '''
Bendy API ported to Forge
But you should use Fabric or Quilt
'''
#logoFile = ""

[[dependencies.bendylib]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"
